### PR TITLE
Re-implement Mouse.Target for debugger mouse highlight

### LINKED ISSUE #67: Debugger mouse highlight doesn't work with local character
Due to `Mouse.Target` intrinsically ignoring the local character

### PR DESCRIPTION
**Pull request by jackTabsCode**
Fixes #67

### CODE REVIEW

File: lib/debugger/mouseHighlight.lua [hunk 1]
```diff
@@ -2,6 +2,19 @@ local UserInputService = game:GetService("UserInputService")
...
+function getInstanceOnMouse()
+	local camera = workspace.CurrentCamera
+	if not camera then
+		return
+	end
+
+	local mouseLocation = UserInputService:GetMouseLocation()
+	local ray = camera:ScreenPointToRay(mouseLocation.X, mouseLocation.Y)
+
+	local result = workspace:Raycast(ray.Origin, ray.Direction * 1000)
```
Comment (jackTabsCode) [inline lib/debugger/mouseHighlight.lua:14]: 1000 seems like a sensible length, but not sure.

**Comment by Ukendio** [comment]
LGTM on the implementation! I understand the rationale of #67. Quite often that the local character is part of an entity in the game world, so allowing inspecting/tool-tip on it makes a lot of sense to me.
